export const SET_SKIN ="SET_SKIN";
export const UPDATE_SKIN ="UPDATE_SKIN";
export const ADD_CONTACT ="ADD_CONTACT";
export const UPDATE_CONTACT ="UPDATE_CONTACT";
export const ADD_CONTACT_ERROR ="ADD_CONTACT_ERROR";
export const UPDATE_CONTACT_ERROR ="UPDATE_CONTACT_ERROR";

export const ADD_EDUCATION ="ADD_EDUCATION";
export const UPDATE_EDUCATION ="UPDATE_EDUCATION";
export const ADD_FONT_FAMILY ="ADD_FONT_FAMILY";
export const UPDATE_FONT_FAMILY ="UPDATE_FONT_FAMILY";
export const SET_MAIL ="SET_EMAIL";
export const SET_PASSWORD ="SET_PASSWORD";
export const UPDATE_MAIL ="UPDATE_MAIL";

